export const ProductActionTypes = {

  GET_PRODUCTLIST: "GET_PRODUCTLIST",
  SET_PRODUCTLIST: "SET_PRODUCTLIST",
  SEARCH_PRODUCTLIST: "SEARCH_PRODUCTLIST",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS"
}
