
export const CartActionTypes = {

  GET_CART_ITEMS: "GET_CART_ITEMS",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART: "UPDATE_CART",
  DELETE_CART_ITEM: "DELETE_CART_ITEM"
}
